server:
  port: 8081
  servlet:
    session:
      timeout: 1

spring:
  application:
    name: spring-security

  datasource:
    url: jdbc:mysql://47.98.60.41:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    type: com.zaxxer.hikari.HikariDataSource
  session:
    store-type: redis
  redis:
    host: 47.98.60.41
    port: 6379
    password: root

#custom:
#  security:
#    browser:
#      loginPage: /demo.html
#custom:
#  security:
#    browser:
#      loginType: REDIRECT
#custom:
#  security:
#    code:
#      image:
#        length: 6
#        url: /user/*




